### ISSUE TITLE
Change pxpxN array into Nxpxp

### ISSUE THREAD

**Issue by irenecrsn** [irenecrsn/gmat#10]
So that when returning vectorized form it is more consistent

**Comment by gherardovarando** [comment]
I agree but on the other side the p x p x N array is consistent with BDgraph package
https://cran.r-project.org/web/packages/BDgraph/BDgraph.pdf

**Comment by irenecrsn** [comment]
We will keep it as `pxpxN` then, since now vectorization is a separate functionality (see #37)
