### ISSUE TITLE
unify return values: either covariances or correlations

### ISSUE THREAD

**Issue by irenecrsn** [irenecrsn/gmat#25]

**Comment by irenecrsn** [comment]
Warning: `port` and `diagdom` return covariance matrices, while `chol_` functions return correlation. I prefer not to change this for this CRAN release, to be consistent with the PGM paper for now, what do you think @gherardovarando?

**Comment by irenecrsn** [comment]
I mean, we can implement this, but for next version together with the algorithmic changes in orthogonalization (in branch `port-upd`)

**Comment by gherardovarando** [comment]
I leave it to you, but as a long term goal I would prefer to just return correlations (if there is not a specific reason not to do so)

**Comment by irenecrsn** [comment]
Ok, we will do so for the next one, possibly allowing the user to choose

**Comment by irenecrsn** [comment]
Also names of functions should be improved now that Uniform and Partial orthogonalization methods are interacting. And possibly revisit arguments and their default values.

**Comment by gherardovarando** [comment]
now `port` should return correlation matrices, since the normalization has been embedded in the Gram-Schmidt step. Right?

**Comment by irenecrsn** [comment]
> now `port` should return correlation matrices, since the normalization has been embedded in the Gram-Schmidt step. Right?

Yes, and diagdom has been changed in #66. I am going to leave the parameter and function name changes for a future release though. When I think #66 is finished I will ask you for a review.
