### ISSUE TITLE
rgmat function appear in doc

### ISSUE THREAD

**Issue by gherardovarando** [irenecrsn/gmat#3]
From the documentation it seems there exist a function called ``rgmat`` . 
I think the guilty line is more or less [here](https://github.com/irenecrsn/gmat/blob/b8570e3736b49c11cffc7d696193e02d2e7654bb/R/functions.R#L6)

**Comment by irenecrsn** [comment]
OK, this is not a bug, `rgmat` is the name given to the "group" of documentation of both `port` and `diagdom`. However, we could use a more descriptive name instead of `rgmat`.

**Comment by irenecrsn** [comment]
Let me know if you like the new name, so I can close this issue, or either propose a new one if you think of another description that fits better.

**Comment by gherardovarando** [comment]
I agree with new name.
