### ISSUE TITLE
chordal is not testing v-structures

### ISSUE THREAD

**Issue by gherardovarando** [irenecrsn/gmat#33]

**Comment by irenecrsn** [comment]
With this you meant the function `igraph::isChordal`, right?

**Comment by gherardovarando** [comment]
yes, I mean the word we were using where misleading.

**Comment by irenecrsn** [comment]
OK, then now we have the same problem, (https://irenecrsn.github.io/gmat/reference/cor_dag.html#arguments). I will take a look.
